### ISSUE TITLE
running with wifibroadcast pipeline

### ISSUE THREAD

**Issue by natxopedreira** [fthiery/gst-oculus-fpv#1]
Hi

Im trying to use your repo to view a [wifibroadcast](https://befinitiv.wordpress.com/wifibroadcast-analog-like-transmission-of-live-video-data/) pipeline on ubuntu but having problems.

Your code its working ok, i clone your repo and im able to run and view a videotest screen with oculus distortion.

The problem comes when i want to view a "wifibroadcast pipeline" im trying with a pipeline:
`pipeline_source = 'fdsrc ! h264parse ! avdec_h264 '`

and i get that error on console :
`0:00:11.688785969  2164      0x22c74a0 WARN                   pango gstbasetextoverlay.c:2909:gst_base_text_overlay_video_chain:<timeoverlay> buffer without timestamp, discarding`

im sure that the wifibroadcast pipeline its ok as im able to view on gstreamer :
`gst-launch-1.0 -v fdsrc ! h264parse ! avdec_h264 !  xvimagesink sync=false`

Can you give me some clues about what im doing wrong???

Thanks!!

**Comment by natxopedreira** [comment]
Ok, i change the pipeline_preprocess_pattern and now im receiving the stream.

I see the image a little stretched.... my stream its 1280x720 and seems like its resized to 4:3 or something like that, its that possible?

**Comment by fthiery** [comment]
Hi

If i understand correctly, you are using a raspberrypi-based emitter, using the prebuilt image from https://github.com/befinitiv/rpi_wifibroadcast_image_builder/releases/tag/v0.4, which uses the raspberrypi camera to stream h264 encoded video over RTP/UDP (guessing here); then you run some software that outputs on an fd, which you then feed into this pipeline ?

Can you paste the output of gst-launch-1.0 -v fdsrc ! h264parse ! avdec_h264 ! xvimagesink sync=false ?

**Comment by natxopedreira** [comment]
Hello

I have it working, but i see a image a little stretched... my stream its 1280X720 and im using a oculus dk1 1280x800, don't know if its important.

Yep im using a rpi on TX with a rpi camera, and a ubuntu on RX part. it streams raw h264... not rtp and not under udp or tcp. I don't know enough to give a technical explain on how that works but its very cool kind of transmission, if you fly fpv take a look. Im running a fpv car with it, and the best part its that when signal degrade you don't get "frozen frames" you get "noise" like an analog transmission, very low latency and hight resolution.

The flow its as you describe, i run a software on my ubuntu RX which assemble the frame and feed on the gstreamer pipeline. 

I don't have the system at home, i can post the info on monday, the changes i made to your script a snapshot of what im seeing and the output of the gstreamer pipeline you ask for.

Also i used this script but not oculus shader so i use a 110fov lens on the rpi camera, even i tried to send two cameras signal to get 3d video (super cool) https://github.com/natxopedreira/fpv-stream-to-vr but your version its better as you use a shader to create the rift view.


Thanks for reply!
